configs:
  lingerTimeMs: "10"
  topic: "cdctest/astracdc/data-342690fc-0ec9-4025-8c4e-d0966f71ecd1-sample.all_accounts"
  sanitizeTopicName: "true"
  kafkaConnectorConfigProperties:
    autoCreateTables: "true"
    bufferSize: "10"
    connector.class: "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector"
    defaultDataset: "astracdc_demo"
    kafkaDataFieldName: "topicMetaData"
    keySource: "JSON"
    keyfile: "{\"type\": \"service_account\",\"project_id\": \"bq-test-382615\",\"private_key_id\": \"**redacted**\",\"private_key\": \"-----BEGIN PRIVATE KEY-----\\n**redacted**\\n-----END PRIVATE KEY-----\\n\",\"client_email\": \"**redacted\",\"client_id\": \"**redacted**\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/redacted.iam.gserviceaccount.com\"}"
    name: "bq-demo"
    project: "bq-test-382615"
    queueSize: "100"
    sanitizeFieldNames: "true"
    sanitizeTopics: "false"
    tasks.max: "1"
    topics: "cdctest/astracdc/data-342690fc-0ec9-4025-8c4e-d0966f71ecd1-sample.all_accounts"
    kafkaKeyFieldName: "key"
    topic2TableMap: "persistent___cdctest_astracdc_data_342690fc_0ec9_4025_8c4e_d0966f71ecd1_sample_all_accounts_partition_0:all_accounts_partition_0,persistent___cdctest_astracdc_data_342690fc_0ec9_4025_8c4e_d0966f71ecd1_sample_all_accounts_partition_1:all_accounts_partition_1,persistent___cdctest_astracdc_data_342690fc_0ec9_4025_8c4e_d0966f71ecd1_sample_all_accounts_partition_2:all_accounts_partition_2"
    allowNewBigQueryFields: "true"
  batchSize: "10"
  offsetStorageTopic: "cdctest/astracdc/bq-demo-offset-01"
  kafkaConnectorSinkClass: "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector"